language: node_js
node_js:
- '6'
install:
- npm install --no-optional
script:
- npm test
before_deploy: npm run package
deploy:
  - provider: releases
    api_key:
      secure: ikEYQQEjYENp6xiBVKaqKzppKJGq+HNdRKle55ymfODg0f/kCGGAlTkQDAh275koFoVbG02c2iz2TaS/F/UaHtSlNswf3g9pzpv76Kw7yyey/txEJ044nbd9V7Z3sxRIpr/vDSQ94bhmwzxi8qN3wJpIGGaBfHc7tLUqY41e1KMWGs/dHWkbKL8+cav3xkoBd39tNfV267oClWpdb7xccf2mW2iZH6AgHU03jhsE2kQkaXuUL0G5VuqkKIvPMZFQM+R2AYtLf+mgF5/dV8OpRxibn2F0wLzAVmkGwaGgDaUubd42oa7B/B6emINzCTh4boRN/dzAjWt7ZQKnkS4Uda830w1qSobRzWOaCXhuW33OrcVUbdkicvgoliCAhotNtnFRd6wZkmPrLy/TdZo+6Xh35UaSEIexX0ifvjD+iLnbttBxb+5EFiurYqaXz1v/9Fh0azGqZsWOs+TgRoXN59zWEC/F2Ggs0x3/K1sy2POVDWlJyKQRo7Qq/IOuycJpCfgExCRL+CLnBg4M9inEO+/71cXBhgnPjzXQsdy8+qdaKuYFm4Gb5t6D2RRKdUaJN6hhlR1otSE9TCLD49rMk6TUxtn+OndCpvh8LTyLcTU+Ed11kDJh5IKASIxUyDkUQNGkdSLwuLmWC6j5pVQdJdCzf5EXj/UCXq8d+CfkFSw=
    file: dist/app.zip
    on:
      repo: DeskproApps/app-installer
  - provider: npm
    api_key: $NPM_TOKEN
    email: radu.helstern@gmail.com
    skip_cleanup: true
    on:
      tags: true
