language: node_js
node_js:
  - '8'
before_install:
  - if [ ! -z "$ARTIFACTS_BUCKET" ] && [ ! -z "ARTIFACTS_KEY" ] && [ ! -z "ARTIFACTS_SECRET" ] ; then export UPLOAD_ARTIFACT=yes ; else echo artifact uploading is disabled; fi
install:
  - NODE_ENV=dev yarn install
  - if [ ! -z "$UPLOAD_ARTIFACT" ]; then curl -sL https://raw.githubusercontent.com/travis-ci/artifacts/master/install | bash; fi
  - if [ ! -z "$UPLOAD_ARTIFACT" ]; then yarn add @deskpro/apps-ci-tools; fi
script:
  - yarn test --ci --resetMocks && CI=false yarn build && mv ./build/app.zip app.zip
cache:
  yarn: true
  directories:
    - node_modules
after_success:
  - if [ ! -z "$UPLOAD_ARTIFACT" ] ; then artifacts upload --target-paths /${TRAVIS_REPO_SLUG}/${TRAVIS_BUILD_NUMBER}/NODE-${TRAVIS_NODE_VERSION} app.zip ; fi
  - if [ ! -z "$UPLOAD_ARTIFACT" ] && [ ! -z "$TRAVIS_PULL_REQUEST_SLUG" ] ; then node node_modules/.bin/dpbuild -- travis pr-comment . --s3target /${TRAVIS_REPO_SLUG}/${TRAVIS_BUILD_NUMBER}/NODE-${TRAVIS_NODE_VERSION} ; fi
deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file: app.zip
    skip_cleanup: true
    on:
      repo: deskpro/apps-installer
      tags: true
  - provider: npm
    api_key: $NPM_TOKEN
    email: radu.helstern@gmail.com
    skip_cleanup: true
    on:
      tags: true
